# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='depth',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='path',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
