# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_menuitem_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Use url to page of this content type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_menuitem', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='custom_url',
            field=models.CharField(blank=True, help_text='any url if content type and pbject ID not specified', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='object_pk',
            field=models.IntegerField(blank=True, help_text='Select object of selected content type', null=True, verbose_name='object ID'),
        ),
    ]
