# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20160406_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='nofollow',
            field=models.BooleanField(default=False, help_text='for seo purposes'),
        ),
    ]
