# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collection_point',
            field=models.SmallIntegerField(choices=[(1, 'Ophalen Ootmarsumsestraat 352 - Almelo'), (2, 'Ophalen Vincent van Goghplein 21 - Almelo'), (3, 'Ophalen Hogepad 1/86 (winkelcentrum de Hoge Wal) - Rijssen')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(1, 'Betalen bij afhalen (Betalen met pin mogelijk)'), (2, 'iDEAL')], default=1),
            preserve_default=False,
        ),
    ]
