# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 22:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import products.models
import utils.local_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, storage=utils.local_storage.MyLocalStorage(), upload_to=products.models.get_image_path2)),
                ('user_image', models.ImageField(blank=True, null=True, storage=utils.local_storage.MyLocalStorage(), upload_to=products.models.get_image_path3)),
                ('image_scale', models.FloatField(blank=True, default=1)),
                ('image_top', models.IntegerField(blank=True, default=0)),
                ('image_left', models.IntegerField(blank=True, default=0)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('font_type', models.CharField(blank=True, max_length=255)),
                ('font_size', models.IntegerField(blank=True, default=12)),
                ('font_color', models.CharField(blank=True, default='#000', max_length=16)),
                ('text_top', models.IntegerField(blank=True, default=0)),
                ('text_left', models.IntegerField(blank=True, default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=utils.local_storage.MyLocalStorage(), upload_to=products.models.get_image_path)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
